ecosystem:
  main_project: drools
  projects:
  - name: drools
    regexs:
    - drools.*
  - name: kie-benchmarks
    ignore_release: true
    ignore_productization: true
    regexs:
    - kie-benchmarks.*
git:
  branches:
  - name: test-config
    main_branch: true
seed:
  config_file:
    git:
      repository: drools
      author:
        name: radtriste
        credentials_id: kie-ci
      branch: test-config
    path: .ci/jenkins/config/branch.yaml
  jenkinsfile: dsl/seed/jenkinsfiles/Jenkinsfile.seed.branch
jenkins:
  email_creds_id: KOGITO_CI_EMAIL_TO_PERSO # TODO to update to DROOLS_EMAIL_CI and add in Jenkins
