ecosystem:
  main_project: drools
  projects:
  - name: drools
    regexs:
    - drools.*
git:
  branches:
  - name: setup_env_rewrite_pr_job
    main_branch: true
seed:
  config_file:
    git:
      repository: drools
      author:
        name: radtriste
        credentials_id: kie-ci
      branch: setup_env_rewrite_pr_job
    path: .ci/jenkins/config/branch.yaml
  jenkinsfile: dsl/seed/jenkinsfiles/Jenkinsfile.seed.branch
jenkins:
  email_creds_id: KOGITO_CI_EMAIL_TO_PERSO # TODO to update to DROOLS_EMAIL_CI and add in Jenkins
